name: LaunchDarkly Code References

on:
  push:
    branches: [main]

jobs:
  code-refs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download ld-find-code-refs binary (v1.8.6)
        run: |
          curl -sSL https://github.com/launchdarkly/ld-find-code-refs/releases/download/v1.8.6/ld-find-code-refs-linux-amd64 -o ld-find-code-refs
          chmod +x ld-find-code-refs

      - name: Run ld-find-code-refs
        env:
          LD_ACCESS_TOKEN: ${{ secrets.LD_ACCESS_TOKEN }}
        run: |
          ./ld-find-code-refs \
            --proj-key your-project-key \
            --repo-name "${{ github.repository }}" \
            --dir . \
            --ref ${{ github.ref_name }} \
